# Generated by Django 5.0.3 on 2024-03-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('p', 'Projekt'), ('l', 'Laboratorium'), ('c', 'Cwiczenia')], max_length=1),
        ),
    ]
